services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "3333:3333"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - beamz
    networks:
      - beamz-network

  beamz:
    image: ghcr.io/renzynx/beamz
    container_name: beamz
    environment:
      - NODE_ENV=production
      # DO NOT change this environment variable
      - BASE_URL=http://localhost:3333
      - SECRET=32-characters-random-string-for-secret
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    networks:
      - beamz-network

networks:
  beamz-network:
    driver: bridge
