services:
  haproxy:
    image: haproxy:2.8-alpine
    container_name: haproxy
    # Proxy listens on host port 3333 and forwards requests to the Beamz services.
    # IMPORTANT: Ensure /api/* is forwarded to the API (beamz:3333) and all other
    # routes are forwarded to the web server (beamz:3000).
    ports:
      - "3333:3333"
      - "8404:8404" # HAProxy stats page
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - beamz
    networks:
      - beamz-network

  beamz:
    image: ghcr.io/renzynx/beamz
    container_name: beamz
    environment:
      - NODE_ENV=production
      - BASE_URL=http://example.com # The URL you are deploying to
      - SECRET=32-characters-random-string-for-secret
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    networks:
      - beamz-network

networks:
  beamz-network:
    driver: bridge
